# Force HTTPS (good hygiene)
[[redirects]]
  from = "http://vaibhavmehta.me/*"
  to = "https://vaibhavmehta.me/:splat"
  status = 301
  force = true

# (Optional) also catch http://www → https
[[redirects]]
  from = "http://www.vaibhavmehta.me/*"
  to = "https://vaibhavmehta.me/:splat"
  status = 301
  force = true

# Return 404 for common WP/scanner paths
[[redirects]]
  from = "/xmlrpc.php"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/wp-includes/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*/wp-includes/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/llms.txt"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/js/twint_ch.js"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/js/lkk_ch.js"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/css/support_parent.css"
  to = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
